services:
  postgres:
    image: 'postgres:15'
    container_name: the_brew_postgres
    restart: always
    environment:
      - POSTGRES_DB=thebrew
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the_brew_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thebrew
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
